### ISSUE TITLE
Move media assets on PUT instead of copy

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-server#18]
Currently when we PUT an image and thumbnail we copy them into the media folder. This is going to result in duplicates of all images (and thumbnails).

We should move these files instead to avoid duplicates.

We could leave it to the client to delete the files after putting them to the server, but this will not be as performant since generally a file move is faster than a copy then delete.

@karissa any thoughts?
@noffle would you be able to implement this? We don't need this urgently, I think it's fine to have duplicates for now.

**Comment by noffle** [comment]
Done (as of 6.0.0).

**Comment by noffle** [comment]
@gmaclennan Sure, I can put this in.

Concern: I wonder if uxers will find it confusing that photos they take don't appear in the gallery. cc @aliya-ryan

**Comment by aliya-ryan** [comment]
@noffle @gmaclennan not sure I'm understanding completely. If this means that when users use MM and take photos that are attached to points these photos are not stored in the gallery but only within the MM app, I think this would be fine and would not confuse people. I don't think we want duplicates of photos as that is more likely to cause confusion (we lost a whole lot of photos from Guyana because of something related to this).

But perhaps you mean something else entirely?

**Comment by noffle** [comment]
@aliya-ryan You understood 100% completely. Thank you!

**Comment by gmaclennan** [comment]
This was resolved long ago, closing now
